### ISSUE TITLE
[Bug]: Make Website Responsive

### ISSUE THREAD

**Issue by iDharitri-Raj** [GameSphere-MultiPlayer/Dot-Box#1]
### Give a brief about the bug ✍️

The current version is not responsive, which means it does not adapt well to different screen sizes and devices. This can lead to a poor user experience, particularly for visitors accessing the website on mobile devices or smaller screens.
![Screenshot 2024-05-09 140518](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/144556385/ff42bb8b-7272-4f0d-bf93-4a9d361ac233)

### What is the expected behavior? 🤔

- The website should be responsive and fluidly adapt to different screen sizes, including desktops, laptops, tablets, and mobile phone.
- Content should be organized and displayed in a user-friendly manner, ensuring readability and ease of navigation across all devices.

### Provide step by step information reproduce the bug 📄

I'll implement responsive design principles using CSS media queries to adjust the layout, typography, and styling based on the viewport size.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by suraj-9849** [comment]
I would like to work on this issue. Can u please assign this to me!. I will make it responsive for all the mobile devices

**Comment by Yuvika-14** [comment]
Please assign me this issue

**Comment by krishnas005** [comment]
I can make it responsive. I have a good experience with CSS and Frontend Development. Please assign me this issue under GSSOC'24.

**Comment by Adi-gitX** [comment]
I would like to solve this issue by adding the requried media queries and adding Viewport Meta Tag which can help in making the page responsive, Please assign me this issue

**Comment by michellecordovi** [comment]
Please assign this issue to me as I would like to contribute under GSSoC'24 .  I can make this website responsive via grid/flexbox layout, media queries, and adjusting the format for desktop, tablet, and mobile devices.

**Comment by BhargavTammana** [comment]
Hi, I am confident in my skills of responsive design can you assign it to me I want to contribute under GSSoC'24

**Comment by akilesh1706** [comment]
@iDharitri-Raj I would like to work on this issue as part of GSSoC'24. I request you to assign it to me. Thanks!

**Comment by Mohit5Upadhyay** [comment]
I want to work under the GSSoC'24. Please assign the task of making responsiveness to me . I will surely make it responsive and adding the hover effect and to enhance the UI of the web application.

**Comment by Durgesh4993** [comment]
@krishnas005 @akilesh1706 @JanitKumar @Mohit5Upadhyay @BhargavTammana @michellecordovi Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by krishnas005** [comment]
@Durgesh4993 Please check issue #26 raised by me

**Comment by Divya-1612-reddy** [comment]
please assign me this issue
