### ISSUE TITLE
[New Feature]: Add Home button 

### ISSUE THREAD

**Issue by MrPC7** [GameSphere-MultiPlayer/Dot-Box#108]
### Feature Request:
As a user, I would like to have a "Home" button in the game interface so that I can easily navigate back to the main page of the website.

### Details:
- Currently, there is no option to navigate back to the main page of the website from within the game interface.
- Adding a "Home" button will enhance the user experience by allowing them to easily return to the main page without having to use the browser's back button.

### Acceptance Criteria:
- [ ] A "Home" button is added to the game interface.
- [ ] Clicking on the "Home" button navigates the user back to the main page of the website.
- [ ] The button is clearly visible and accessible to the user during gameplay.

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@MrPC7 This issue is already assigned to someone else...

Please raise any other issues
