### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Princegupta101** [GameSphere-MultiPlayer/Dot-Box#11]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign me this task.

**Comment by Durgesh4993** [comment]
@suhanipaliwal Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
