### ISSUE TITLE
No exit/restart button to leave on-going game 

### ISSUE THREAD

**Issue by Priyal208** [GameSphere-MultiPlayer/Dot-Box#115]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

There is absence of exit / restart button, once entered in the game user has no option but to close website in order to exit the game or restart the game

### Describe the solution you'd like

I can implement exit and re-start buttons in the game so that users can replay the game or exit the game in between without leaving the website completely, pls assign to me under gssoc'24 

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Priyal208 This issue is already assigned to someone else...

Please raise any other issues
