### ISSUE TITLE
[Enhancement]: Home page 

### ISSUE THREAD

**Issue by Naitikkumar2003** [GameSphere-MultiPlayer/Dot-Box#117]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement: home page can be better .css is to simple and not attractive 

### Describe the solution you'd like

Solution steps: assign me to improve css of your home page which attract more user.we can change the color and place to make more attractive 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
Please raise any other issue, because someone is already working on it
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
