### ISSUE TITLE
[Bug]: Even if user enters 1 as the number of Players, the game just starts off as 2 player game.

### ISSUE THREAD

**Issue by anandpanda** [GameSphere-MultiPlayer/Dot-Box#125]
Please assign me this issue under the Gssoc contributions, as i am capable of solving it.

### Give a brief about the bug ✍️

 Even if user enters 1 as the number of Players, the game just starts off as 2 player game.
 
![image](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/148877270/1aaceb62-440a-4e0a-95de-d84187da7964)
![image](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/148877270/1d445a80-eae1-437d-80a1-2a8e0969259e)

### What is the expected behavior? 🤔

The game should give warn the user and prevent the game from starting if number of players entered is less than 2.

### Provide step by step information reproduce the bug 📄

Just enter number of player as 1 and hit the start button.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by anandpanda** [comment]
I am a contributor for GSSoC'24, so please assign me this issue.

**Comment by Lovelyfin00** [comment]
This is a validation issue and looks good

**Comment by anandpanda** [comment]
Thank you for the assignment.
Will do my best.

**Comment by LAKSHYA1509** [comment]
Hi ... This is a simple error And i will be happy to do it .. Please assign this issue to me

**Comment by anandpanda** [comment]
I have made a pull request #181 . Please have a look at it and let me know if it need improvements..
