### ISSUE TITLE
[New Feature]: Add Theme Switcher Button to Change Background Video

### ISSUE THREAD

**Issue by aditya-bhaumik** [GameSphere-MultiPlayer/Dot-Box#160]
### 🎮 feature Request

The feature adds a theme switcher button to the website, allowing users to choose between different background videos. When the user clicks the theme switcher button, a dropdown with theme options appears. Selecting a theme changes the background video to the corresponding choice. 

This feature will add more background theme for the user such as waterfall, nature, etc. This will help in improving user experience by providing the user options for customizing the background of the website. 

I will add a background folder to the project directory, which will contain all the background videos. This folder will be referenced in the code to dynamically switch between different video backgrounds based on the selected theme.

### Point down the features

 Theme Switcher Button: A button labeled "Change Theme" to allow users to access different background themes.
 Theme Options Dropdown: A dropdown menu with multiple theme options that change the background video when selected.
 Background Video Switching: Different background videos are loaded and played based on the selected theme.
 Overlay Container: An overlay container with a semi-transparent background to ensure content visibility over the background videos.
Enhanced Readability: Improved text color and visibility for better contrast and readability against varying background videos.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Lovelyfin00** [comment]
This is a nice suggestion 👍

**Comment by Siddhi561** [comment]
Hey, can you please assign me this issue if it is not solved? This is my first time making an open-source contribution, and I really want to showcase my skills. I am very familiar with languages like Java, HTML, CSS, and JS. Apart from coding, I'm an ux/ui freelancer as well.

**Comment by Lovelyfin00** [comment]
Hi @Siddhi561 
Can you take a look at other issues? This has just been assigned. I recently created a simple issue that might interest you, Do take a look
