### ISSUE TITLE
[New Feature]: Adding the mute button 

### ISSUE THREAD

**Issue by thevijayshankersharma** [GameSphere-MultiPlayer/Dot-Box#17]
I've taken a look at this issue and I'm interested in working on it. Could you please assign this issue to me so that I can start working on it?

**Comment by abhivarma174** [comment]
I can add mute button. Kindly assign me this issue under GSSOC'24

**Comment by Pooja-c03** [comment]
please assign this issue to me for adding the button

**Comment by AshutoshKumar0206** [comment]
Please  assign me this issue. I can add a mute button with the specific icon in it.

**Comment by crimsonnap004** [comment]
Hello mentor please assign me this issue .i can add a mute with a designing icon.

**Comment by royalrajputayush** [comment]
I want to work on the nav section, please assign me this under gssoc level 2

Record
 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by shnwz-solves** [comment]
Hi, PA, I would like to add this feature. Please assign this project to me under GSSOC'24.

**Comment by Durgesh4993** [comment]
@abhivarma174 @Alokita004 @Pooja-c03 @shnwz-solves @royalrajputayush @AshutoshKumar0206 Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by thevijayshankersharma** [comment]
@Durgesh4993 Hey, I have raised the PR check it out.

**Comment by PoojaGadagi08** [comment]
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by ayush-t02** [comment]
@PoojaGadagi08 this
