### ISSUE TITLE
[Enhancement]: Improve label of the input elements on the landing page

### ISSUE THREAD

**Issue by Lovelyfin00** [GameSphere-MultiPlayer/Dot-Box#170]
## Label not explanatory enough in the current game landing page
The current game has each label as the expected number of values per inputs. This should also indicate which of the input is column or row or number of players

<br/>
<br/>

![image](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/38161296/b0048ad5-7c96-4fbf-90d3-8f3accf58bb7)

### Describe the solution you'd like

I'd like a some enhancement to be made to the label of each input to increase UC. 

- [ ] `Row input`. Label should be `No of Rows` and the placeholder for the input should be `"Enter no of rows"`
- [ ] `Column input`, Label should be `No of Columnss` and the placeholder for the input should be `"Enter no of columns"`
- [ ] `Players Input` Label should be `No of Playerss` and the placeholder for the input should be `"Enter no of players"`

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by sdas1311** [comment]
Assign me this issue. I will solve this issue on the go.

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by supriyagaut** [comment]
please assign me this issue i want to work on this issue

**Comment by mehrun171** [comment]
I would like to work on this issue...Please assign me to this

**Comment by Rpokhariya** [comment]
I would like to make the enhancements to the label of each input. Please assign me the task.

**Comment by RiyaRanka** [comment]
Assign me this issue. I will work on the placeholder and input. In addition I will shirnk the input box a little bit and add border radius to the input box. Put the Between line of each input boxes below the input box thus will create a more user friendly interface.
