### ISSUE TITLE
[Enhancement]: Exit Button in the game

### ISSUE THREAD

**Issue by HimakarC** [GameSphere-MultiPlayer/Dot-Box#177]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

It would be better to add Exit button in the game for more responsive to the user/gamer.

Please assign me this task.

### Describe the solution you'd like

Adding the Exit button
![Screenshot 2024-05-18 093732](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/116370824/ffb133c6-0af4-4c78-ab6d-9edab3a36794)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Tarani12** [comment]
Though we can refresh the page to go back to home page, it will be user-friendly if there will be a 'Exit' button. Please assign me this issue.

**Comment by Seejal03** [comment]
pls assign me this issue

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
