### ISSUE TITLE
Adding a Reset Button 

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [GameSphere-MultiPlayer/Dot-Box#18]
Please assign this issue to me

**Comment by nakshatravyas** [comment]
Hey, I want to contribute to this project as a part of GSSOC 2024. I am a MERN stack developer and I have worked on several projects and won hackathons as well. I can create the feature. 

Here's my linkedin profile : https://www.linkedin.com/in/nakshatravyas/
Github profile : https://github.com/nakshatravyas

**Comment by Snehal3704** [comment]
please assign this issue to me

**Comment by Rashi563** [comment]
Please assign this issue to me.

**Comment by Parishri07** [comment]
I am willing to resolve this issue, please assign this task to me.

**Comment by Muskansahuincredible** [comment]
please assign me this

**Comment by Lalita14ritgithub** [comment]
Hi, 
please assign this task to me, i want to work on it

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by Alokita004** [comment]
Hello sir I am alokita .I have worked various full stack web development project i am really interested to solve this task please assign this task to me.

**Comment by Deekshashakyawal** [comment]
Please assign this issue to me, I have experience in it . I'm eager to contribute to this .

**Comment by royalrajputayush** [comment]
I want to work on the nav section, please assign me this under gssoc level 2

Record
 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by Durgesh4993** [comment]
@Muskansahuincredible @Alokita004 @Deekshashakyawal @royalrajputayush @nakshatravyas @gargimukherjee25 @Lalita14ritgithub @Parishri07 @Rashi563 @Snehal3704 @nakshatravyas @Ishitamukherjee2004 Please raise any other issue, because someone is already working on it

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
