### ISSUE TITLE
Improvement in UI and Design of the website 

### ISSUE THREAD

**Issue by Pujan-sarkar** [GameSphere-MultiPlayer/Dot-Box#19]
![image_2024-05-10_152243385](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/144250917/b356512d-2a79-4a32-849a-08e13c245bbc)

### 🎮 feature Request

> ### Do you want to improve the user experience? 😀 Describe yourself..
> By improvement in UI design of the website and the game
> 
> ### Describe the solution you'd like
> Solution steps -> I want to contribute in this issue and make the UI user friendly attractive and more new.
> 
> ### Select program in which you are contributing
> GSSoC23
> 
> ### Code of Conduct
> * [x]  I follow CONTRIBUTING GUIDELINE of this project.

> @Durgesh4993  will you assign this issue to me please .

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by rajlaxmi03** [comment]
I  would like to contribute

**Comment by ishap11** [comment]
Hello, I'm eager to contribute to Dot-Box project and I'd love to enhance the UI to make it more attractive and engaging.
I've reviewed the current UI and I believe I can make improvements by adding more visual appeal, refining the layout, and possibly introducing animations to enhance user experience. Could you please assign me the task of enhancing the UI? I'm eager to get started and contribute to making this project even better!
Looking forward to your response!
Thankyou!

**Comment by Durgesh4993** [comment]
@Pujan-sarkar @ishap11 @rajlaxmi03 Please raise any other issue, because someone is already working on it

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
