### ISSUE TITLE
[Enhancement]: adding back ground color  and font color

### ISSUE THREAD

**Issue by solanki505** [GameSphere-MultiPlayer/Dot-Box#2]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement by adding color to make appearance of site better.

### Describe the solution you'd like

Solution steps ->I would like to work on this issue by adding background color and text color.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by anushkapal28** [comment]
I've noticed an opportunity to enhance the project's aesthetics by adding background and font colors. Mind if I contribute these changes?

**Comment by aditimishra0013** [comment]
Please assign this issue to me. I want to contribute in this project

**Comment by samikshaa001** [comment]
I am interested in making the website a little more attractive and responsive.
Requesting to assign me this issue to me

**Comment by Vika0408** [comment]
Please assign this issue to me for the GSSOC24. I would like to make the UI of this website more interesting and creative.

**Comment by Yuvika-14** [comment]
please assign me this issue

**Comment by nidhaahmed** [comment]
Hello there!

I'm excited about the opportunity to enhance the game by adding background color and font color (#2). Improving the appearance of the site can greatly enhance the overall user experience and make the game more visually appealing.

I'd love to take on this task and work on implementing the solution steps by adding background color and text color. This involves carefully selecting color schemes that complement each other and align with the game's theme, ensuring a cohesive and visually pleasing design.

Looking forward to diving into this enhancement and contributing to the game's aesthetic appeal!

Best regards,
Nidha Ahmed Mohammad

**Comment by Harsh-Vardhan-Yadav-03** [comment]
I can solve this issue , please assign this this to me

**Comment by rajsingh19** [comment]
I am experienced in web development, having designed various websites and contributed to college club websites. I can help solve issues by adding background and font colors effectively. Please assign me this issue.

**Comment by BhargavTammana** [comment]
Hi, I am a beginner in web development and I am eager to learn new things and implement them for which I find open very useful
I would like work on this and explore much more possibilities and creativity

Solution ->
I want to enhance the dashboard by adding solid back ground colors if possible gradient back ground color and 
add hover features to input fields, create card for instructions making it more appealing and also a lot more changes to make it look user friendly and intuitive

assign this task to me I would like to contribute under GSSoC'2024

I promise to follow the Code of Conduct

**Comment by Muskansahuincredible** [comment]
Please assign me

**Comment by mdramijzamadar** [comment]
Please assign this project.

**Comment by 20ankur07** [comment]
Hey, I think the aesthetics of the game can be improved more to increase user experience so I request you to assign me as to showcase my my experience.

**Comment by Paavni-Goyal** [comment]
Hey, I would like to work on the same. Can you please assign this to me.

**Comment by Durgesh4993** [comment]
@Muskansahuincredible @nidhaahmed @20ankur07 @mdramijzamadar @Paavni-Goyal @mdramijzamadar @BhargavTammana Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Divya-1612-reddy** [comment]
please assign me this issue
