### ISSUE TITLE
Update the documentation to show that all PRs opened for GSSOC should point to the develop branch

### ISSUE THREAD

**Issue by Lovelyfin00** [GameSphere-MultiPlayer/Dot-Box#200]
### Describe the bug ✍️

Currently most PRs that are opened are also pointed to the main branch and that's not what the maintainers want for GSSOC

### Provide step by step information reproduce the bug 📄

Include in the documentation that all PRs should point to the `develop1 branch. And also when creating new branches that they want to work on, it should be while they're on the develop branch. This would make it easier for the maintainers when reviewing and merging PRs

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Lovelyfin00** [comment]
Hi @sdas1311 
This is the resaon why. You'd have to checkout to develop before you can see the latest merged changes

**Comment by sdas1311** [comment]
> Hi @sdas1311 This is the resaon why. You'd have to checkout to develop before you can see the latest merged changes

My task is to : Include in the main branch documentation that all PRs should point to the `develop1 branch ?

**Comment by Lovelyfin00** [comment]
Yes

**Comment by sdas1311** [comment]
I created a PR for this issue, can you please review it?

> Develop branch and also when create a new branch on their fork, they should be checked out to develop and not main. So they can get the latest changes

I created a PR for this issue, can you please review it?

**Comment by nihasinghania22** [comment]
hi! could you please assign me this issue.

**Comment by sdas1311** [comment]
> Develop branch and also when create a new branch on their fork, they should be checked out to develop and not main. So they can get the latest changes

hi @Lovelyfin00 , I created a PR for this issue 2 days ago, can you please review it?
