### ISSUE TITLE
[Bug]: The change theme button is not working

### ISSUE THREAD

**Issue by Aditi22Bansal** [GameSphere-MultiPlayer/Dot-Box#202]
### Give a brief about the bug ✍️

Description

The change theme button is not working when clicked 

### What is the expected behavior? 🤔

Description
I'll code it to change theme from dark mode to light mode and vice-a-vera by making it a toggle button 

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Aditi22Bansal** [comment]
@Lovelyfin00 
Kindly assign me this issue and labels

**Comment by Lovelyfin00** [comment]
I just checked and the change theme button is working
