### ISSUE TITLE
Readme.md [Documentation Bug]: 

### ISSUE THREAD

**Issue by Meetjain1** [GameSphere-MultiPlayer/Dot-Box#218]
### Describe the bug ✍️

Currently readme.md is not fascinating and appealing, 

### Provide step by step information reproduce the bug 📄

It lacks our working video of our project , contributors section etc
@ayush-t02 assign this issue to me I will create a fully new version of Readme.md file .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Anjankumarkamalapur** [comment]
I wanted to update Readme section can you please assign this to me.

**Comment by ayush-t02** [comment]
documentation is important, make sure to be crisp. Focus on good fonts and indendations.
