### ISSUE TITLE
Missing Learn.md [Documentation Bug]: 

### ISSUE THREAD

**Issue by Meetjain1** [GameSphere-MultiPlayer/Dot-Box#219]
### Describe the bug ✍️

Learn.md file is missing, In our current repositoy 

@ayush-t02 assign this issue to me I will add this file

### Provide step by step information reproduce the bug 📄

DescriptionThe learn.md file in GitHub is typically used as a resource to provide guidance, tutorials, or educational content related to a specific repository. This file can serve various purposes, such as introducing new users to the project, providing detailed instructions for using the codebase, or offering learning pathways for different topics covered by the repository

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-t02** [comment]
documentation is important, make sure to be crisp. Focus on good fonts and indendations.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
