### ISSUE TITLE
[Enhancement]: Add a button to return to the home page 

### ISSUE THREAD

**Issue by kumarharshh** [GameSphere-MultiPlayer/Dot-Box#23]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement :
There should be a button if the user decides in between to back to the home screen and readjust the settings.

### Describe the solution you'd like

Solution steps
I can add a button which will take you back to the home page.

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by kumarharshh** [comment]
Hi, 
Can you please assign this issue to me? I'm contributing under GSSOC'24 program.

**Comment by AshutoshKumar0206** [comment]
Please assign this issue to me. I can add a button written exit on it which will take yes or no as input to return to home page or not.

**Comment by anythingkartik** [comment]
Hi, 
I am Kartik and I want to work on issue #23, which is adding a button to return to the home page
I will locate the HTML file where you want to add the button( index.html) or where the home page content is defined and I will write relative path to your home page.
Here is Linkedln https://www.linkedin.com/in/itskartikgupta/

**Comment by Harshdev098** [comment]
Hi,
I want to work on this issue. Can you please assign it to me.

**Comment by Lalita14ritgithub** [comment]
Hi,
I would like to work on this issue please assign this task to me

**Comment by kvdevlopment** [comment]
Hello, I'm a GSSOC'24 contributor

I would like to work on the same. Can you please assign this to me.

**Comment by Durgesh4993** [comment]
@kumarharshh @kvdevlopment @Harshdev098 @anythingkartik @AshutoshKumar0206 Please raise any other issue, because someone is already working on it.

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
