### ISSUE TITLE
[Enhancement]: Disable the Start Game button, if Players <2

### ISSUE THREAD

**Issue by kumarharshh** [GameSphere-MultiPlayer/Dot-Box#24]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
The start button should be disabled, if the user has added the value for players below 2, and also the user should get this as error message above the input field

### Describe the solution you'd like

Solution steps
I can disable the button with a condition that depends on the number of players entered in the field, also the error message can be achieved by error handling.

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by kumarharshh** [comment]
Hi, 
Can I fix this issue? I'm contributing under GSSOC'24 program.

**Comment by kumarharshh** [comment]
Hi,
Can you please assign this issue to me I can fix this? 
I'm contributing under GSSOC'24 program

**Comment by kumarharshh** [comment]
@Durgesh4993 can you please assign this issue to me? I'm contributing under GSSoC'24 program

**Comment by Durgesh4993** [comment]
@kumarharshh Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
