### ISSUE TITLE
Add Reset Button to Return to Initial Stage of the Game

### ISSUE THREAD

**Issue by krishnas005** [GameSphere-MultiPlayer/Dot-Box#26]
### 🎮 feature Request

The reset button, when clicked, will:

- Clear the entire game board, removing all completed boxes and moves.
- Reset any game-related variables, scores, and player turns to their default values.
- Optionally, show a confirmation dialog to avoid accidental resets.

### Point down the features

- Quick Game Restart: Allows players to instantly reset the game and start over.
- Confirmation Prompt: A prompt to ensure players are aware of the reset action, reducing the chance of accidental loss of progress.
- Consistent Game State: Resets the game to a consistent starting point, ensuring all players have a fair chance at a fresh game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by krishnas005** [comment]
@Durgesh4993 Please assign me this issue under GSSOC'24

**Comment by anshmanitripathi** [comment]
Please assign this task to me , i want to work upon this under GSSOC'24.

**Comment by Lalita14ritgithub** [comment]
I want to work on this, please assign this task to me.

**Comment by MOULYVINAYAKA** [comment]
Could you please assign this feature #26 to me under Gssoc'24? I am looking forward to working on it and contributing to the project's success

**Comment by shnwz-solves** [comment]
Hi @krishnas005 , I would like to contribute to this issue. Please assign me.

**Comment by Unknownmaster0** [comment]
I would work upon the reset button addition and its functionality.

**Comment by Unknownmaster0** [comment]
I would like to work upon the add reset button and it's functionality

**Comment by Durgesh4993** [comment]
@MOULYVINAYAKA @krishnas005 @Unknownmaster0 @anshmanitripathi  @shnwz-solves @Lalita14ritgithub Please raise any other issue, because someone is already working on this issue.

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
