### ISSUE TITLE
[New Feature]: Volume Rocker and Mute Button Integration

### ISSUE THREAD

**Issue by pratikgurjar** [GameSphere-MultiPlayer/Dot-Box#30]
### 🎮 feature Request

feature logic and basic description:

Allow users to adjust sound volume and mute sound within the game interface for a seamless gaming experience.

### Point down the features

**Feature Points:**
Increase/Decrease Sound:
Usage: Allows users to adjust the volume of the game's sound.
Example: Users can click on the volume up/down buttons or slide a volume control slider to increase or decrease the sound level while playing the game.

Mute Sound:
Usage: Enables users to mute/unmute the sound of the game.
Example: Users can click on a mute/unmute button to toggle between muting and unmuting the game's sound.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by MOULYVINAYAKA** [comment]
hello @pratikgurjar, Could you please assign this new feature #30  to me under Gssoc'24? I am looking forward to working on it and contributing to the project's success

**Comment by Harshdev098** [comment]
Hii,
I want to work on this issue, can you please assign it to me

**Comment by pratikgurjar** [comment]
> hello @pratikgurjar, Could you please assign this new feature #30 to me under Gssoc'24? I am looking forward to working on it and contributing to the project's success

Hi @MOULYVINAYAKA, I don't have authority to assign you this task. I'm also a contributor, please tag respected admin

**Comment by Durgesh4993** [comment]
@pratikgurjar @MOULYVINAYAKA @Harshdev098 Please raise any other issue, because someone is already working on this issue.

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
