### ISSUE TITLE
[Enhancement]:  Enhance game by making UI attractive and user friendly.

### ISSUE THREAD

**Issue by kanishka-parmar** [GameSphere-MultiPlayer/Dot-Box#31]
### Description 

![Screenshot 2024-05-11 100351](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/114792553/27e4ebf3-3ed1-4208-a42c-138b22231dc0)

The main page does not attract the users. As it is the game page it should be attractive and the user should easily navigate to , replay the game, and change the configuration such as rows, columns, and no of players.

### Describe the solution you'd like

Solution steps
I want to add a nav bar on site which will provide different options like 
->Restart the game
->Change configuration such as rows columns and no of players
->Exit the game

I want to contribute to this under GSSOC'24.

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by kanishka-parmar** [comment]
@Durgesh4993 Please assign this to me. I want to contribute under GSSOC'24.

**Comment by kvdevlopment** [comment]
Hello, I'm a GSSOC'24 contributor

I would like to work on the same. Can you please assign this to me.

**Comment by ishap11** [comment]
Hello, I'm eager to contribute to the Dot-Box project by enhancing the UI. I believe I can improve its visual appeal, layout, and user experience. Could you assign me this task? I want to contribute under GSSOC'24.Thankyou!

**Comment by Pujan-sarkar** [comment]
@Durgesh4993 can you give a reply about this issue please?

**Comment by Durgesh4993** [comment]
@kvdevlopment @kanishka-parmar @ishap11 @Pujan-sarkar Please raise any other issue, because someone is already working on this issue.

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
