### ISSUE TITLE
[Enhancement]: Coloring of the lines

### ISSUE THREAD

**Issue by VijaySamant4368** [GameSphere-MultiPlayer/Dot-Box#33]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
Currently all the lines are black, which makes it hard to remember who drew which line.
![Screenshot 2024-05-11 105334](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/145102345/b87914fc-823f-406f-8f12-0ca5f294436b)

### Describe the solution you'd like

Solution steps:
The lines should be colored the same color as the player color
The issue can be resolved using CSS, and I believe I am qualified enough to resolve it

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by motuncoded** [comment]
I am a GSSOC, I would like to contribute to this issue by coloring the lines

**Comment by shrashti2004** [comment]
I would like to contribute to this issue by coloring the lines , Under GSSOC 2024

**Comment by kvdevlopment** [comment]
"Hi @VijaySamant4368 
I've been following the development of this project closely and I'm eager to contribute. Could you please assign me to work on this particular project? I believe I can make valuable contributions to its enhancement. Looking forward to being part of the team!"

**Comment by Yashc885** [comment]
i would like to resolve this issue

**Comment by Durgesh4993** [comment]
@motuncoded @kvdevlopment @shrashti2004 @VijaySamant4368 @Yashc885 Please raise any other issue, because someone is already working on this issue.

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
