### ISSUE TITLE
Add labels to existing issues

### ISSUE THREAD

**Issue by Deekshashakyawal** [GameSphere-MultiPlayer/Dot-Box#37]
Add labels like level1 , level 2 or level 3 on issues

**Comment by shnwz-solves** [comment]
Hey, Deekshashakyawal please assign me this issue.

**Comment by kvdevlopment** [comment]
Hello, I'm a GSSOC'24 contributor

I would like to work on the same. Can you please assign this to me.

**Comment by Durgesh4993** [comment]
@kvdevlopment @Deekshashakyawal @shnwz-solves we have proper leves 

Please raise any other issue, i'll assign you..
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
