### ISSUE TITLE
[New Feature]: Adding a footer section

### ISSUE THREAD

**Issue by AyushShukla3466** [GameSphere-MultiPlayer/Dot-Box#47]
### 🎮 feature Request

Footers are important because they provide users with additional navigation options, important links, contact information, and other relevant details, enhancing website usability, accessibility, and overall user experience.

### Point down the features

It typically contain contact information, social links, and supplementary navigation.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Shubhra-Narang** [comment]
Kindly assign me this issue ,I can contribute to this

**Comment by kvdevlopment** [comment]
"Hello @AyushShukla3466 
 I've been following the progress of this project with great interest and enthusiasm. I would love the opportunity to contribute to this particular project. Could you please assign me to work on it? I'm eager to bring my skills and dedication to the team and help make this project even better. Looking forward to your response!"

**Comment by ankiiitagupta** [comment]
@AyushShukla3466  Can you please assign this task to me under GSSOC'24? I would love to work on it. I want to use my skills and provide you with desired and enhanced result.

**Comment by muskantanwar7** [comment]
@AyushShukla3466 Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand
kindly assign this issue to me

**Comment by Durgesh4993** [comment]
@AyushShukla3466 @ankiiitagupta @kvdevlopment @Shubhra-Narang @muskantanwar7 Please raise any other issue, i'll assign you..
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
