### ISSUE TITLE
Music ON and OFF Button 

### ISSUE THREAD

**Issue by GOURAVSINGH19** [GameSphere-MultiPlayer/Dot-Box#49]
### 🎮 feature Request

feature logic and basic description
![Screenshot 2024-05-11 205700](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/120244528/4d1c49db-cecc-4ad0-9341-fe21de5530a9)

we can made a music on off btn on top of page may be it is good things to give choice to user . user  want to listen music or not ...

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by GOURAVSINGH19** [comment]
If you think it is good feature then assigned me.

**Comment by Saksham1411** [comment]
As a GSsoc'24 contributor. I want to address this issue. I request you to assign this to me @GOURAVSINGH19

**Comment by GOURAVSINGH19** [comment]
brother  I am also a GSsoc'24 contributor.

**Comment by Durgesh4993** [comment]
@GOURAVSINGH19 @Saksham1411 Please raise any other issue, because someone is already working on this issue.
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
