### ISSUE TITLE
[Bug]: The game will start even if we set rows,columns and player to 1

### ISSUE THREAD

**Issue by Pratik2401** [GameSphere-MultiPlayer/Dot-Box#50]
### Give a brief about the bug ✍️

The game will start even if the the values of rows,columns and player is set to 1.

### What is the expected behavior? 🤔

min player should be 2 
min box size should be 5*5

### Provide step by step information reproduce the bug 📄

set rows,columns and player to 1
![image](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/105542579/c2fb3ed7-26f4-4168-a738-d61585a28dbe)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Pratik2401** [comment]
pls assign me these issue under GSSOC'24

**Comment by yash21sriv** [comment]
please assign me this issue @Durgesh4993

**Comment by Yashc885** [comment]
i would like to resolve this issue

**Comment by Durgesh4993** [comment]
@yash21sriv @Pratik2401 @Yashc885 Please raise any other issue, because someone is already working on this issue.
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
