### ISSUE TITLE
[New Feature]: Improving the font and colour combination.

### ISSUE THREAD

**Issue by Anou25** [GameSphere-MultiPlayer/Dot-Box#54]
### 🎮 feature Request

The font and the color palate chosen is not visually appealing and attreactive.

### Point down the features

Point down the features
1. Want to make UI design more exiting for a Game user interface
2. Add more colors which will be suitable for the game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

@Durgesh4993 please can you assign this to me.

**Comment by Shreesanyog** [comment]
### Issue#54

**Description**
As a participant in the GirlScript Summer of Code (GSSoC'24), I'm looking to contribute to Dot-Box by enhancing the UI to offer a better visual appeal and gameplay experience.

**Proposed Enhancements**
- **UI Aesthetics**: Update the UI elements to be more engaging and in tune with the game's theme.
- **User Experience**: Improve navigation and interaction design for a seamless player experience.

Please give me a chance to contribute in this and also please mention GSSoC and level

**Comment by codewithganeshhh** [comment]
Hi 
I want to work on this issue. Could you please assign me this issue.

**Comment by Durgesh4993** [comment]
@Anou25 @codewithganeshhh @Shreesanyog Please raise any other issue, i'll assign you...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
