### ISSUE TITLE
[New Feature]: Add Dark Mode Functionality, optimizations for game script.

### ISSUE THREAD

**Issue by moroii69** [GameSphere-MultiPlayer/Dot-Box#63]
### Solution steps:

1. **Optimization**: 
- **ES6** shorthand property names can be utilized in the constructor for clearer property declarations.
- implement object restructuring in the constructor parameters for improved clarity.
- simplify the logic of the `getLastRemainingEdge()` method using `Object.values()`. encapsulated UI creation logic within the createUI() method for better organization and readability.
- move constant declarations outside the event listener function to prevent repeated declarations.
- precomputation of game parameters like **rows**, **columns**, and **player count** outside the game constructor to avoid unnecessary calculations.
- used `requestAnimationFrame` for UI updates to enhance performance and ensure smoother animations.
- cached **DOM** queries outside functions where they are frequently accessed to reduce redundancy.
- tested the optimized script thoroughly to ensure it maintains the same functionality as the original script. ✔️ 
- verified that all game features, including player switching, box filling, and game over conditions, work as expected. ✔️ 

2. **Dark Theme for Home Page and Game Page:**
- add styles for the dark mode **toggle** button, allowing users to switch between **light** 🌙  and **dark** 🌑 themes conveniently.
- update styles 🖌️ for various elements across the application to ensure consistency and readability in both light and dark modes.
- **benefit** - enhanced accessibility by adjusting color schemes and contrast ratios to improve readability and usability for all users. (including shadow for the board in both light and dark modes).

### Game enhancement:

1. several optimizations for the existing game script can be implemented, the optimizations focus on improving performance, readability. script performance can be improved by optimizing DOM queries and reducing redundant calculations. utilized ES6 shorthand property names in the constructor can be used for clearer property declarations.

2. dark mode functionality can be added for both home page and game page (interchangeable between dark and light modes with a toggle button). styles can be updated for various elements across the application to ensure consistency and readability in both light and dark modes.

Home Page (Dark Mode)
![home-page-dark](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/74895423/9fc7a32c-0ac2-4abd-8899-a387ed6be9c1)

Board Game Page (Dark Mode)
![board-game-page-dark](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/74895423/0edafb38-909d-4b5e-aa79-653eacb07ec8)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project

**Code Ready for PR. Please assign me the issue.**

**Comment by 39palakved** [comment]
I would like to work on this issue . Please assign this task to me .

**Comment by Durgesh4993** [comment]
@moroii69 @39palakved Please raise any other issue, i'll assign you...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
