### ISSUE TITLE
[New Feature]: Adding NEW GAME button

### ISSUE THREAD

**Issue by madhurima316** [GameSphere-MultiPlayer/Dot-Box#65]
### 🎮 feature Request

I would like to add a NEW GAME button.

### Point down the features

Adding a NEW GAME button would enable restarting the game after finishing a round or even in between the game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by madhurima316** [comment]
Please assign me this issue under GSSoC24.

**Comment by Durgesh4993** [comment]
@madhurima316 Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
