### ISSUE TITLE
inupt the player names and display on screen 

### ISSUE THREAD

**Issue by HimanshiGoel10** [GameSphere-MultiPlayer/Dot-Box#67]
### 🎮 feature Request

we will take the users's names and instead of player1 and player2 , we will display the actual names

### Point down the features

will look better

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by HimanshiGoel10** [comment]
Please assign this issue raised by me under gssoc'24, i can work well on it

**Comment by Durgesh4993** [comment]
@HimanshiGoel10 Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
