### ISSUE TITLE
[New Feature]: Adding Exit Button to back to home

### ISSUE THREAD

**Issue by Harshdev098** [GameSphere-MultiPlayer/Dot-Box#68]
### 🎮 feature Request

feature logic and basic description

### Point down the features

feature points
- Added exit Button on game page.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Harshdev098** [comment]
@Durgesh4993 Can you please review my pr

**Comment by Durgesh4993** [comment]
@Harshdev098 Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
