### ISSUE TITLE
[Enhancement]: Enhancing Rows,col's,players filelds UI

### ISSUE THREAD

**Issue by Rohitha-pudu** [GameSphere-MultiPlayer/Dot-Box#76]
### The User Experience of the landing page fields is not quite well
enhancing them by providing like this can improve UX
![image](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/116823590/687471ad-fa3d-4362-89b7-fbfcff7112a2)
I will Work on this issue.Please Assign it to me
#Gssoc24

**Comment by Durgesh4993** [comment]
@Rohitha-pudu Please raise any other issue, because someone is already working on it
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
