### ISSUE TITLE
[New Feature]: Edit the name of players .

### ISSUE THREAD

**Issue by kanishka-parmar** [GameSphere-MultiPlayer/Dot-Box#77]
### 🎮 feature Request

feature logic and basic description
Having their names in the game helps players to show interest rather than player 1 and player 2 i.e. by default provided.

![Screenshot 2024-05-13 001345](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/114792553/4a4a7923-aaf3-4e13-98c0-aecd620cbb11)

### Point down the features

feature points
Instead of by default names i.e. player 1....6, I would like to add an option to edit their name as they like.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by kanishka-parmar** [comment]
@Durgesh4993 Can you please assign me this under GSSOC'24

**Comment by Durgesh4993** [comment]
@kanishka-parmar Please raise any other issue, because someone is already working on it
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by kanishka-parmar** [comment]
I didn't find any issue related to this. How will I come to know that someone is already working or not?
