### ISSUE TITLE
[New Feature]: Adding Undo Button and the Reset Button.

### ISSUE THREAD

**Issue by surya1926** [GameSphere-MultiPlayer/Dot-Box#78]
### 🎮 feature Request

 Basic description:-

Adding the Undo Button 
Adding the reset button below the Game matrix (Box)

### Point down the features

feature points:-

while clicking one the undo button the player move will be removed it was helpful while the player has checked the wrong dot by mistakenly.
While clicking on the Reset Button the game will be start freshly. These feature will be helpful when the opponent was doing cheating we can reset the game and we can play from starting.
![Screenshot 2024-05-13 005436](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/110684511/8f3b161e-dc7a-490e-8f35-53eba6913557)

Please sir @Durgesh4993  assign me this task, i will make it.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by surya1926** [comment]
Please @Durgesh4993 sir assign me this task.

**Comment by Durgesh4993** [comment]
@surya1926 Please raise any other issue, because someone is already working on it
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
