### ISSUE TITLE
[New Feature]: Back to Home button

### ISSUE THREAD

**Issue by dishathakurata** [GameSphere-MultiPlayer/Dot-Box#85]
### 🎮 feature Request

Back to 'Home' button is required to restart the game or skip the game.

### Point down the features

A button which redirects to homepage.

Assign me to fix this issue under GSSoC '24

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@dishathakurata Please raise any other issue, because someone is already working on it
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
