### ISSUE TITLE
[Documentation enhancement ]: Update Documentation 

### ISSUE THREAD

**Issue by Harman8815** [GameSphere-MultiPlayer/Dot-Box#87]
### Problem
The current documentation lacks a rule book and information about the game, making it challenging for new players to understand and enjoy the game.

### Proposed Solution
I plan to enhance the user experience by adding a comprehensive rule book and detailed information about the game to the documentation. This will include sections such as an overview of the game, detailed rules, setup instructions, gameplay description, FAQs, and tips and strategies. By providing this information, I aim to make it easier for new players to learn and enjoy the game.

### Implementation Steps
1. Create a new section in the documentation for the rule book and game information.
2. Write detailed rules and instructions for the game.
3. Include setup instructions, gameplay description, FAQs, and tips and strategies.
4. Update the documentation with the new information.

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Harman8815** [comment]
Please assign me this

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Harman8815** [comment]
okay got it
