### ISSUE TITLE
[New Feature]: adding the restart or return to home button once the game is finished.

### ISSUE THREAD

**Issue by creativeadi** [GameSphere-MultiPlayer/Dot-Box#89]
### 🎮 feature Request

feature logic and basic description

After the game is finished, the player must be given an option to either restart the game or to go back to the home page.
<img width="1440" alt="Screenshot 2024-05-13 at 3 51 36 PM" src="https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/153895524/4575225b-7ee1-4c79-badd-99a59f010a97">

### Point down the features

feature points

Restart or Return to menu option once the game is finished,

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@creativeadi Please raise any other issue, because someone is already working on it
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
