### ISSUE TITLE
[Enhancement]: Replacing placeholder

### ISSUE THREAD

**Issue by dishathakurata** [GameSphere-MultiPlayer/Dot-Box#92]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement:
Removing default values from rows, columns and players, and adding placeholder like "Enter number of rows, columns or players" will be more appealing
![placeholder](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/146114938/a425a00c-563f-479b-9339-289d5774313f)

### Describe the solution you'd like

Solution steps:
Removing default value option, and adding placeholder option.

Assign me to fix this issue under GSSoC '24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by me-techshruti54212** [comment]
i would like to work upon this issue.please assign it to me.
