### ISSUE TITLE
Improve navbar

### ISSUE THREAD

**Issue by 39palakved** [GameSphere-MultiPlayer/Dot-Box#96]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

I would like to change the fonts, backgrounds, and alignments within input boxes to give off those sleek game vibes.
can you please assign me this task.

### Describe the solution you'd like

I would like to change the fonts, backgrounds, and alignments within input boxes to give off those sleek game vibes.
can you please assign me this task.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Priyanjali24** [comment]
I would like to work o this project. Please assign to me

**Comment by Ipeeka** [comment]
I would like to work o this project. Please assign to me
