### ISSUE TITLE
[New Feature]: After Game Completion there is no restart button!

### ISSUE THREAD

**Issue by Coder-Kartikey** [GameSphere-MultiPlayer/Dot-Box#97]
### 🎮 feature Request

When the game is completed it should have a restart button so that player can play again and again.

### Point down the features

I will add the restart button on right side of the table so that if the user wants to restart the game in the middle of the game or after completion of the game he can easily do it 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Coder-Kartikey** [comment]
@Durgesh4993 Assign this task to me after that i will start working on it immediately .

**Comment by ShravaniPathak** [comment]
I would like to work on this issue. Please assign this task to me

**Comment by Durgesh4993** [comment]
@Coder-Kartikey this issue is already assigned to someone else...

Please raise any other issues
